Json fájfeldolgozás, GitHub Actions beállítása
Teaching-projects/SZE-MOSZE-2020-Pottyok pull request #2
Opened 2020-09-24 07:28 UTC by tamasori

Megírtuk a _parseUnit_ statikus metódust, amely egy fájlnevet vár, ami _json_ kiterjesztésű, és a benne található adatok alapján létrehoz egy _Entity_ példányt. A _json_ adatokat egy _regex_ segítségével dolgozza fel a program.

Emellett beállítottunk egy automatikus buildelést és tesztet a _GitHub Actions_ segítségével, ami a kimenetet vizsgálva dönti el, hogy a program a várt eredményeket hozza-e. Mellékeltünk 3db teszt egységet _json_ formátumban a _units_ mappában.

2020-09-24 16:02 UTC, hegyhati requested changes
Par pici aprosag.

2020-09-24 16:02 UTC, hegyhati commented on .github/workflows/test.yml
> +        run: sudo sh tests.sh
sudo sh?!

2020-09-24 16:02 UTC, hegyhati commented on Entity.cpp
> +#include <regex>
nocsak :-)

2020-09-24 16:02 UTC, hegyhati commented on Entity.cpp
> +    std::ifstream f("units/"+fileName);
Hu, ezt ne, semmikeppen nem a kodba tennem be azt a logikat, hogy milyen konyvtarban vannak a unitok. Legyen eleresi uttal megadva a file.

2020-09-24 16:02 UTC, hegyhati commented on Entity.cpp
> +    const std::regex searchRegex("\"([a-zA-Z0-9]*)\"[\\s:]*\"?([a-zA-Z0-9]*)\"?,?");
csak fyi, megeszi ez aaz is, hogy `"dmg" : "13`
Ami nagyobb baj, hogy azt jol latom, hogy tobb kettospontot is megeszik? Azt azert javitsuk ki.

2020-09-24 16:02 UTC, hegyhati commented on Entity.cpp
> +            attackDamage = stoi(searchMatches[2]);
ez is inkabb elif

2020-09-24 16:02 UTC, hegyhati commented on Entity.cpp
> +    return toCreate;
ezt akkor mar dobd be egy sorba.

2020-09-24 16:02 UTC, hegyhati commented on Entity.cpp
>  std::string Entity::getName(){
const?

2020-09-24 16:02 UTC, hegyhati commented on Entity.h
> +        static Entity parseUnit(const std::string);
lemasolni is felesleges a fajlnevet.

2020-09-24 16:02 UTC, hegyhati commented on README.md
> +./a kakarott.json sally.json
szegeny Sally :worried:

2020-09-24 16:02 UTC, hegyhati commented on main.cpp
> +        }
Ha elhasal a dolog, akar igy, akar ugy, akkor nem kellene 0-val visszaterni. Illetve azt jol ertem, hogy akkor is csinalsz Gam-et, ha elszallt? Azt nem kellene.

2020-09-24 16:02 UTC, hegyhati commented on units/expected.txt
> +kakarott;sally;Kakarott wins. Remaining HP: 20
Nem teljesen felel meg a specifikacionak ugye, de elfer.

2020-09-24 18:10 UTC, mushukcha commented
@hegyhati Megcsináltuk a kért változtatásokat.

2020-09-25 13:43 UTC, hegyhati requested changes

2020-09-25 13:43 UTC, hegyhati commented on Entity.cpp
> +const std::string Entity::getName(){
Jajj.... na a constozast tessek atgondolni. azt nem ertem, hogy ez elso korben hogy nem jott ki.

2020-09-25 13:43 UTC, hegyhati commented on Entity.h
> +        static Entity parseUnit(const std::string&);
Aprosag, de vizualisan jobb, ha a static fuggvenyek nem a non-staticokkal vannak osszemosva.

2020-09-27 12:46 UTC, tamasori commented
@hegyhati Rendberaktuk a constokat

2020-10-01 12:08 UTC, hegyhati requested changes
na meg egy kor const.

2020-10-01 12:08 UTC, hegyhati commented on Game.cpp
> +const bool Game::isAnyoneDead(){
na ez mar megint.... ami fentebb ment, itt miert nem?

2020-10-01 12:08 UTC, hegyhati commented on Game.cpp
> +const Entity Game::getWinner(){
ugyszint.

2020-10-01 16:23 UTC, balintxd commented
@hegyhati Kijavítottuk a maradék két constot.

2020-10-03 10:33 UTC, hegyhati approved these changes

2020-10-03 10:33 UTC, merged