Svg rendering
Teaching-projects/SZE-MOSZE-2020-Pottyok pull request #22
Opened 2020-12-04 14:18 UTC by mushukcha

2020-12-04 15:10 UTC, tamasori requested changes

2020-12-04 15:10 UTC, tamasori commented on CharacterSVGRenderer.cpp
> +                std::string monsterTextureFileName = game.getMonstersHere(j,i).getTexture();
Ez csak 1 Monstert ad vissza ahogy nézem, a név elég megtévesztő lehet.

2020-12-04 15:10 UTC, tamasori commented on Game.cpp
> +        render();
Üres a render függvény. Ezeknek a Prepared game helyett itt kéne lennie a leírás alapján.

2020-12-04 15:10 UTC, tamasori commented on Game.h
> +        Monster getMonstersHere(unsigned int, unsigned int) const;
Ugyan az a probléma, hogy a név megtévesztő.

2020-12-04 15:10 UTC, tamasori commented on PreparedGame.cpp
> +}
Mint említettem, ezeknek a Game osztályban kellene lenniük.

2020-12-04 18:05 UTC, balintxd commented
@tamasori szerintem megoldottam a problemakat, nezz majd ra ;)

2020-12-05 08:41 UTC, tamasori approved these changes

2020-12-05 08:41 UTC, merged