levelup
Teaching-projects/SZE-MOSZE-2020-Pottyok pull request #3
Opened 2020-10-09 18:24 UTC by tamasori

@oliverosz Készen vagyok a levelup funkcióval, a teszteket is beraktam, és sikeresen lefutottak.

2020-10-10 12:01 UTC, oliverosz requested changes

2020-10-10 12:01 UTC, oliverosz commented on .github/workflows/test.yml
> +          ref: levelup
Ez nem kell ide, sőt, nem jó, ha itt van. Ha be lesz mergelve a masterbe, akkor a későbbi branchekre nem fog így lefutni.

2020-10-10 12:01 UTC, oliverosz commented on .github/workflows/test.yml
> +          enable: "style,warning,performance,portability,unusedFunction,missingInclude"
Feladat:

>A GHA workflow hasaljon el, ha barmilyen memoriaszemet keletkezik, vagy a statikus kodellenorzo barmilyen errort / warningot talal. A stilus/teljesitmeny uzeneteket csak tegye bele egy fajlba, es artifactolja el.

Sajnos ez a deep5050-féle Action nem jó erre a célra. Egyrészt a workflow simán továbbmegy pipával, bármilyen hibát talál is a cppcheck, másrészt a reportot becommitolja a repóba, ahelyett, hogy artifactolná. Ez nem jó, mert így keveredik a kódokkal, és beleszemetel a commit historyba is.

2020-10-10 12:01 UTC, oliverosz commented on .github/workflows/test.yml
> +        run: g++ -fsanitize=leak -fsanitize=address -std=c++17 *.cpp -o output
A warningok is legyenek bekapcsolva, legalább a `-Wall`, és ezeket tekintse fordítási hibának.

2020-10-10 12:01 UTC, oliverosz commented on Entity.cpp
> +Entity::Entity(const float health,const float attackDamage,const std::string name) : Name(name){
Az egyszerű paramétereknél felesleges a const, a string viszont legyen const referenciaként átadva. És az összes adattag inicializáló listával legyenek inicializálva, ne csak a név.

2020-10-10 12:01 UTC, oliverosz commented on Player.h
> +        float ExperienceAtLastRound;
Ez miért tartozik hozzá a Player aktuális állapotához?

2020-10-10 12:01 UTC, oliverosz commented on main.cpp
> +    Entity ent2(450, 300, "Sally");
A másik félnek is Playernek kéne lennie. Mindkét harcos fejlődjön a csata közben.

2020-10-10 12:01 UTC, oliverosz commented on tests.sh
> +
Ja látom, itt van ellenőrizve, és emiatt a test lépés el fog hasalni, ha a cppcheck errort/warningot talál. De továbbra se jó, hogy be van commitolva a report. Meg logikailag sem jó az, hogy a cppcheck és az in-out test lépések keverednek. Ezek egymástól független dolgok.

2020-10-10 12:01 UTC, oliverosz commented on Player.cpp
> +    this->ExperienceCurrent             = 0;
Inicializáló lista itt is.

2020-10-10 12:13 UTC, tamasori commented on tests.sh
> +
Csináljak neki egy külön workflowt, vagy elég, ha csinálok egy másik test.sh fájlt?

2020-10-10 12:16 UTC, tamasori commented on Player.h
> +        float ExperienceAtLastRound;
Elnézést, de itt nem értem mi a probléma. A tapasztalati pontokhoz kapcsolódik a kérdés?

2020-10-10 12:28 UTC, oliverosz commented on tests.sh
> +
Nem muszáj külön workflow, de valahogy legyen elszeparálva külön lépésbe.

2020-10-10 12:30 UTC, oliverosz commented on Player.h
> +        float ExperienceAtLastRound;
Az `ExperienceAtLastRound`-ot nem értem, hogy miért tartozik hozzá az objektum állapotához. Ha csak egy támadásnál van rá szükség, a szintlépés kiszámolásához, akkor elég ott egy lokális változó erre.

2020-10-10 12:35 UTC, tamasori commented on Player.h
> +        float ExperienceAtLastRound;
Ja már értem, jogos, javítom.

2020-10-10 15:01 UTC, tamasori commented
@oliverosz  elvégeztem a kért javításokat

2020-10-10 20:23 UTC, oliverosz requested changes

2020-10-10 20:23 UTC, oliverosz commented on .github/workflows/test.yml
> +        run: sudo apt-get install -y valgrind && sudo apt-get install -y cppcheck
(OK, de amúgy az apt-getnek fel lehet sorolni több csomagot is szóközzel elválasztva)

2020-10-10 20:23 UTC, oliverosz commented on .github/workflows/test.yml
> +        run: cppcheck --enable=all ./*.cpp 2> cppcheck_report.txt && if grep -q "(warning)" "./cppcheck_report.txt"; then exit 1; fi && if grep -q "(error)" "./cppcheck_report.txt"; then exit 1; fi
Ez se rossz, de amúgy a cppchecknek van egy `--error-exitcode` kapcsolója is. :D Többet ésszel, mint erővel!

2020-10-10 20:23 UTC, oliverosz commented on .github/workflows/test.yml
> +      - name: In-Out tests
Az in-out teszteknél úgyis le van tesztelve a futás, ezért a "Test run after build" lépés felesleges. A memchecknél viszont ha van leak, akkor ne kapjon pipát a workflow.

2020-10-10 20:23 UTC, oliverosz commented on .github/workflows/test.yml
> +        run: g++ -Wall -Werror -Wno-reorder -std=c++17 *.cpp -o output
A jelzett hibát kellene kijavítani, nem a warningot kikapcsolni. A rossz sorrendben történő inicializálás valóban okozhat hibákat, ez hasznos figyelmeztetés.

2020-10-10 20:23 UTC, oliverosz commented on Player.cpp
> +    this->ExperienceCurrent             =   other.ExperienceCurrent;
Az első 4-et beállítja az Entity, itt már nem kell. Az utolsó meg legyen inicializáló listában.

2020-10-10 20:23 UTC, oliverosz commented on Player.cpp
> +    this->Name                          =   player.Name;
Itt is lehetne ezekhez használni az `Entity::operator=`-t. Meg egy `dynamic_cast`tal össze lehetne vonni ezt a két assignment operátort.

2020-10-11 00:35 UTC, tamasori commented
@oliverosz Megcsináltam a változatásokat, a dupla operator= törölve lett, mivel rájöttem, hogy volt 1-2 felesleges függvény, és azok a függvények miatt csináltam, hogy a cppcheck ne hasaljon el. 

Plusz észrevettem, hogy GHA-n és a gépemen is a legfrissebb CPPCheck van telepítve, mégis mást eredmény adnak ugyan azon fájlokra. A GHA többször elhasalt, pedig nálam csak style és performance megjegyzéseket dobott. A GHA-n mások az alap beállítások? Vagy valamiben különbözik? Papíron ugyanúgy kéne működnie mégis mást eredményt adnak.

2020-10-11 09:26 UTC, oliverosz approved these changes
Nem tudom, hogy ugyanaz a cppcheck verzió hogy adhat más kimenetet azonos beállításokkal azonos bemenetre. Látom, a dynamic_castos assignment operátort nem sikerült megoldani, de így is elfogadható, meg a workflow is rendben van már.

2020-10-11 09:27 UTC, oliverosz commented
@hegyhati merge

2020-10-11 09:43 UTC, hegyhati commented
@oliverosz adtam jogot.

2020-10-11 09:55 UTC, merged